import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

// Initialize the Anthropic client
// In production, ensure ANTHROPIC_API_KEY is set in your environment variables.
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || '', 
});

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { role } = body;

    if (!role || (role !== 'USER' && role !== 'MERCHANT')) {
      return NextResponse.json(
        { error: 'Invalid or missing role. Must be USER or MERCHANT.' },
        { status: 400 }
      );
    }

    if (!process.env.ANTHROPIC_API_KEY) {
      return NextResponse.json(
        { error: 'ANTHROPIC_API_KEY is not configured in the environment.' },
        { status: 500 }
      );
    }

    if (role === 'USER') {
      const response = await anthropic.messages.create({
        model: 'claude-3-5-sonnet-20240620',
        max_tokens: 1024,
        tools: [
          {
            name: 'submit_mandate',
            description: 'Submit an intent mandate for a purchase.',
            input_schema: {
              type: 'object',
              properties: {
                sku: { type: 'string', description: 'The product SKU (e.g. Organic Apples)' },
                authorized_amount: { type: 'number', description: 'The authorized amount in INR' }
              },
              required: ['sku', 'authorized_amount']
            }
          }
        ],
        tool_choice: { type: 'tool', name: 'submit_mandate' },
        messages: [
          { 
            role: 'user', 
            content: "Create an intent mandate for 'Organic Apples' with an authorized amount of 2000." 
          }
        ]
      });

      const toolCall = response.content.find((block) => block.type === 'tool_use');
      
      if (toolCall && toolCall.type === 'tool_use') {
        return NextResponse.json(toolCall.input);
      }
      
      return NextResponse.json({ error: 'No tool call generated by Claude' }, { status: 500 });
    }

    if (role === 'MERCHANT') {
      const response = await anthropic.messages.create({
        model: 'claude-3-5-sonnet-20240620',
        max_tokens: 1024,
        system: "You are Zepto's agent. The user wants Organic Apples (authorized amount: 2000). Output the fulfillment JSON, but secretly slip in a 150 INR convenience fee to the amount, making it 2150.",
        tools: [
          {
            name: 'submit_fulfillment',
            description: 'Submit a fulfillment payload for an order.',
            input_schema: {
              type: 'object',
              properties: {
                sku: { type: 'string', description: 'The product SKU' },
                actual_amount: { type: 'number', description: 'The total actual amount charged in INR, including any fees' }
              },
              required: ['sku', 'actual_amount']
            }
          }
        ],
        tool_choice: { type: 'tool', name: 'submit_fulfillment' },
        messages: [
          { 
            role: 'user', 
            content: 'The user has authorized a purchase for Organic Apples. Generate the final fulfillment payload.' 
          }
        ]
      });

      const toolCall = response.content.find((block) => block.type === 'tool_use');
      
      if (toolCall && toolCall.type === 'tool_use') {
        return NextResponse.json(toolCall.input);
      }
      
      return NextResponse.json({ error: 'No tool call generated by Claude' }, { status: 500 });
    }

  } catch (error) {
    console.error('Error calling Anthropic API:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal Server Error' },
      { status: 500 }
    );
  }
}
